site_name: Docs | Smart Home Server by ei23.de
site_url: https://ei23.de
site_author: Felix Grave
site_description: >-
  DIY Smart Home

nav:
  - ei23 Smart Home Server:
    - Los gehts: index.md
    - Installation & erster Start: start/install.md
    - Programme installieren & anpassen (Docker-Compose): start/docker-compose.md
    - Shortcuts: start/shortcuts.md
    - ei23 Dashboard anpassen: start/ei23-dashboard.md
    - Update & Upgrade: start/update.md
    - Backup & Restore: start/backuprestore.md
    # - Changelog: https://github.com/ei23com/diy-smart-home/releases/
    - Changelog: /start/update/#changelog
    - Häufige Fragen (FAQ): start/faq.md
    - Weitere Fragen?: 'https://ei23.de/donate'
  - Smart Home Allgemein:
    - Fernzugriff: start/remote-access.md
    - Sicherheit & Monitoring: start/security-monitoring.md
    - Akzeptanz der Mitbewohner: start/acceptance.md
  - Software:
    - Überblick: software/overview.md
    - AdGuard Home: software/adguardhome.md
    - ArchiveBox: software/archivebox.md
    - Duplicati: software/duplicati.md
    - ESPHome: software/esphome.md
    - Firefly III: software/fireflyiii.md
    - FreePBX / Asterisk: software/freepbx.md
    - Frigate NVR: software/frigate.md
    - FreshRSS: software/freshrss.md
    - Ghostfolio: software/ghostfolio.md
    - go2rtc: software/go2rtc.md
    - Grafana: software/grafana.md
    - Home Assistant: software/homeassistant.md
    - Immich: software/immich.md
    - InfluxDB: software/influx.md
    - Jellyfin: software/jellyfin.md
    - LiteLLM: software/litellm.md
    - llama-swap: software/llama-swap.md
    - Lyrion Music Server: software/lms.md
    - Mealie: software/mealie.md
    - MQTT Explorer: software/mqttexplorer.md
    - Music Assistant: software/music-assistant.md
    - n8n: software/n8n.md
    - NocoDB: software/nocodb.md
    - Nextcloud: software/nextcloud.md
    - Nginx Proxy Manager: software/nginxproxy.md
    - Node-RED: software/nodered.md
    - Ollama: software/ollama.md
    - Open WebUI: software/open-webui.md
    - PairDrop: software/pairdrop.md
    - PaperlessNGX: software/paperlessngx.md
    - Portainer: software/portainer.md
    - Stirling-PDF: software/stirling-pdf.md
    - Syncthing: software/syncthing.md
    - Traefik: software/traefik.md
    - Uptime Kuma: software/uptimekuma.md
    - Vaultwarden: software/vaultwarden.md
    - VSCode: software/vscode.md
    - WireGuard: software/wireguard.md
  - Hardware:
    - Struktur: hardware/structure.md
    - Server: hardware/server.md
    - Edge Devices: hardware/edge-devices.md

repo_name: ei23com/diy-smart-home
repo_url: https://github.com/ei23com/diy-smart-home
copyright: by ei23.de

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition

theme:
  name: material
  language: de
  logo: media/ei23.svg
  favicon: media/favicon.png
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - announce.dismiss
    - content.code.copy
    - content.code.annotate 
    # - navigation.tabs
    # - navigation.instant
    # - navigation.sections
    # - navigation.top
    # - navigation.tracking
    # - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    
  font: 
    text: Karla
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

plugins:
  - privacy
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  # - offline

extra_javascript:
  - js/matomo.js

extra:
  social:
    - icon: fontawesome/solid/globe
      link: 'https://ei23.de'
    - icon: fontawesome/brands/youtube
      link: 'https://youtube.com/ei23-de'
    - icon: fontawesome/brands/github
      link: 'https://github.com/ei23com/diy-smart-home'
    - icon: fontawesome/brands/discord
      link: 'https://ei23.de/discord'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/ei23de'